window.defaultNumber = '+1-000-000-0000';
window.defaultText = 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.';
window.text = {
    'xhamster.com': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'perfectgirls.net': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'gotporn.com': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'anysex.com': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'sex.com': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'bravotube.net': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'mylust.com': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'manporn.xxx': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'anybunny.com': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'txxx.com': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.',
    'findbestsolution.xyz': 'Your  Amazon ID was recently used at the Amazon Store for a $1348 transaction via Amazon Pay (Pre-Authorization). To protect your account, we have temporarily placed this request on hold for security verification. If you did not authorize this purchase, please contact Amazon Support immediately at +1-000-000-0000 to secure your account and prevent unauthorized activity.'
};
